version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alcosi-web
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/alcosi?schema=public
    depends_on:
      - db
    command: npm run dev -- -H 0.0.0.0

  db:
    image: postgres:15-alpine
    container_name: alcosi-db
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alcosi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
